### PR TITLE
update diboson cross sections

### PR DESCRIPTION
**Pull request by jabuschh**
see issue https://github.com/UHH2/UHH2-datasets/issues/254

Please don't merge yet, I'd like to wait for the final confirmation of these values from our GEN contact.

### CODE REVIEW

**Comment by anmalara** [comment]
I'm not convinced you should change the central value. But rather implement is a k factor correction.

**Comment by jabuschh** [comment]
changed it ;)

**Comment by anmalara** [comment]
Thanks, @jabuschh. I'm not sure why the old k-factors were removed from [here](https://github.com/UHH2/UHH2-datasets/blob/7076d172687be2ba9e596dcf5f1ff924d693daed/CrossSectionHelper.py#L84) to [here](https://github.com/UHH2/UHH2-datasets/blob/5a29ede97cc67eb77f0ce819c9f3016cab35ef24/CrossSectionHelper.py#L723), but it's good that now they are back. Compared to the old ones, there is a ~2% change with the final xsec, so it's consistent with EOY numbers.

**Comment by jabuschh** [comment]
I also got the confirmation for these values from our GEN expert, so we're good to go, I guess.

**Comment by jabuschh** [comment]
Shall we merge this then? :)

**Pull request merged**
