### PR TITLE
QCD HT-binned UL16preVFP (two bins still missing)

### PR DESCRIPTION
**Pull request by stalbrec**
This adds the HT-bins of the QCD sample that are ready for UL16preVFP.

As mentioned in the spreadsheet, for this HT-binned sample the production status of the various bins is a bit confusing.
There are duplicate requests for most bins/years, where one always has "*madgraphMLM*" and the other just "*madgraph*" in its name. 

Apparently these are identical and could both be used, although one always has ~twice as much statistics than the other and is done ore still in production. (Overview of all requested samples in [GrASP](https://cms-pdmv.cern.ch/grasp/existing?dataset=QCD_HT*to*_TuneCP5_PSWeights_13TeV-madgraph&name=RunIISummer20UL16*GEN,RunIISummer20UL16*GENAPV,RunIISummer20UL17*GEN,RunIISummer20UL18*GEN&miniaod_version=MiniAODv2))

For the bins 200 to 300 GeV and 300 to 500 GeV both of these requested samples are still either in status `new` or `submitted`. As soon as MiniAODv2 is ready for those i will add them as well.

### CODE REVIEW

**Comment by MatthiesC** [comment]
Thanks for this! Have you checked the cross sections with GenXSecAnalyzer? It makes the most sense if we state a 13TeV cross section (not year-dependent ones) if the results from GenXSecAnalyzer are approx the same across years (ignoring statistical fluctuations in the GenXSecAnalyzer results).

How to GenXSecAnalyzer: https://github.com/UHH2/UHH2/wiki/How-to-use-GenXSecAnalyzer

**Comment by stalbrec** [comment]
Ah right, i wanted to double check the cross-sections, but forgot - thanks for the reminder. checking now and will update the xsecs.

The values that are in our database are from XSDB entries of legacy samples, or where do these numbers come from again?

**Comment by MatthiesC** [comment]
Afaik these are just copied over from pre-UL, so probably not valid for UL

**Comment by stalbrec** [comment]
Alright i got the values from the GenXSecAnalyzer using the UL16preVFP samples.
I was able to compare the 50to100 bin with the respective UL18 sample, and it is consistent within uncertainty (as expected) -> 1.860e+08 +- 1.637e+05 pb
Here are the cross-sections - i will update the missing bins, once they are ready.

||xs[pb]|uncertainty[pb]|
|-|-|-|
|QCD_HT50to100|186171589.270000|163348.827120|
|QCD_HT100to200|23623277.469000|33284.558791|
|QCD_HT200to300|-|-|
|QCD_HT300to500|-|-|
|QCD_HT500to700|30363.051467|29.096102|
|QCD_HT700to1000|6428.868942|6.179750|
|QCD_HT1000to1500|1122.659129|1.078610|
|QCD_HT1500to2000|108.162888|0.104112|
|QCD_HT2000toInf|22.008194|0.027423|

**Comment by MatthiesC** [comment]
Very good! One minor thing: Do you think it makes sense to state in `XsecSource_13TeV` always which year this is from? See the entries for QCD EMEnriched as an example. Could be useful IMO

PS: Good that we checked the xsecs with GenXSecAnalyzer, the values for 50to100 were just copied from 100to200 (ups...)

**Comment by stalbrec** [comment]
Good point! Might be useful - i added the info

**Pull request merged**
