### PR TITLE
[Data UL] Inclusion of DoubleMuon and DoubleEG datasets

### PR DESCRIPTION
**Pull request by bonanomi**
Please check the implementation of `DoubleMuon_RunB` entry in `CrossSectionHelper.py` is compliant to the expectation.

### CODE REVIEW

**Comment by MatthiesC** [comment]
Hi @bonanomi ! Thanks!
In order to keep the same style, the regex-like `{ver1,ver2}` should only appear in the `XmlSource` (resp. the DAS dataset name). Please merge the two XML files into one, calling it `RunII_106X_v2/data/UL16preVFP/DoubleMuon_Run2016B-HIPM_UL2016_MiniAODv2-v1.xml` (similar with DoubleEG), unless you have a concrete reason to distinguish between RunB-ver1 and RunB-ver2. The `get_xml` function will just return the string that you put into the `Xml` field. So, it depends mostly on your implementation resp. how you use the CrossSectionHelper "API" and further process the return value of `get_xml`. But I would propose to keep the style used for the other RunB data sets.

**Comment by bonanomi** [comment]
Hi @MatthiesC , I've just noted that the same applies also to DoubleEG period B primary dataset (still UL16preVFP).
However, differently to the DoubleMuon case, the `ver1` and `ver2` have different `MiniAODv2` versions, namely:
```
DoubleEG_Run2016B-ver1_HIPM_UL2016_MiniAODv2-v1.xml

DoubleEG_Run2016B-ver2_HIPM_UL2016_MiniAODv2-v3.xml
```
I can merge the xml into a single `DoubleEG_Run2016B-ver1_HIPM_UL2016_MiniAODv2.xml` file, but would the syntax `DoubleEG_Run2016B-{ver1,ver2}_HIPM_UL2016_MiniAODv2-{v1,v3}` for the `XmlSource_UL16preVFP` entry in `CrossSectionHelper.py`?

**Comment by MatthiesC** [comment]
Good point. As you suggest, I would just drop the `v*` at the end of the XML file name. For the `XmlSource`, I would then just write `{DoubleEG_Run2016B-ver1_HIPM_UL2016_MiniAODv2-v1,DoubleEG_Run2016B-ver2_HIPM_UL2016_MiniAODv2-v3}`. It makes sense to keep a style that can be interpreted as regex. The `XmlSource` is in first principles only there to keep track of what DAS sample is used (in addition to our spreadsheet). But I can imagine the scenario that one wants to extract all the DAS sample names e.g. for a table in an AN and then it would be cool to have the functionality to extract the DAS names from the database automatically, relying on proper regex for those rare exceptions.

**Comment by bonanomi** [comment]
Done! This should work now.

**Comment by MatthiesC** [comment]
Thanks! Would you also please `git rm` the now redundant XML files for ver1 and ver2? Then I merge

**Pull request merged**
