### PR TITLE
add TTW and TTZ samples

### PR DESCRIPTION
**Pull request by danielhundhausen**

### CODE REVIEW

**Comment by mschrode** [comment]
Hi @danielhundhausen , regarding the sources, these are:
XSec: `Phys. Rev. Lett. 113 (2014) 212001 [doi:10.1103/PhysRevLett.113.212001](https%3A%2F%2Fdx.doi.org%2F10.1140%2Fepjc%2Fs10052-019-6746-z&v=6cfd2325)`
BR: `P.A. Zyla et al. (Particle Data Group), Prog. Theor. Exp. Phys. 2020, 083C01 (2020) and 2021 update https://pdglive.lbl.gov/Viewer.action`
(which is where they were taken from in the AN you correctly linked).

**Comment by MatthiesC** [comment]
Hi @danielhundhausen ! Could you please adopt the formatting of the other entries in the CrossSectionHelper? I.e. no line breaks between Xml and XmlSource of the same year and only one blank line between the dict entries. Of course, this does not change python functionality but having the same formatting everywhere might help to avoid headache later on. After that, I will merge

**Comment by bonanomi** [comment]
RE This: if this can be merged, I can take care of modifying the xsec references and the CrossSectionHelper formatting. I could either create a PR together with the modifications needed for DoubleMuon and DoubleEGamma UL datasets or an independent one. I'd personally go for the latter.

**Comment by mschrode** [comment]
Hi @bonanomi , thanks! I agree, independent PRs would be better. 
@MatthiesC , do you have any objections?

**Comment by mschrode** [comment]
thanks @MatthiesC !

**Comment by bonanomi** [comment]
Thanks! Formatting and references fixed in https://github.com/UHH2/UHH2-datasets/pull/133

**Pull request merged**
