### PR TITLE
SingleMuon dataset, except Run2018A (need to re-run)

### PR DESCRIPTION
**Pull request by mschrode**
Add all UL SingleMuon datasets except Run2018A, which I need to rerun (number events check did fail).

For Run2016B, there are two versions Run2016B-ver1_HIPM and Run2016B-ver2_HIPM, which I concatenated into one xml file. How do we specify the DAS sources in this case? (For now, I put both dataset names comma separated)

### CODE REVIEW

**Comment by MatthiesC** [comment]
Thank you very much for this!

- Could you please give the numbers for UL16preVFP as sum of ver1 and ver2 like `2789243+158145722`
- Regarding the multiple DAS names: We should come up with a convention for this. For JetHT and SinglePhoton, it is written as `{ver1,ver2}`. Probably makes sense to stick to this convention for now until we decide something else

Could you push these two changes, please?

**Comment by mschrode** [comment]
Hi @MatthiesC , thanks for checking, I just committed an update with the requested changes

**Comment by mschrode** [comment]
eh, please ignore, {ver1.. is still wrong, fixing it now

**Comment by mschrode** [comment]
done

**Pull request merged**
