### PR TITLE
Added LQ->tl samples with mixed decays

### PR DESCRIPTION
**Pull request by reimersa**
Added mu+e and e+tau LQ decays

### CODE REVIEW

**Comment by raggleton** [comment]
Does it matter that some of these XML have no ntuples in them?

**Comment by reimersa** [comment]
missing masspoints: 
e+tau: 500, 1400
e+mu: 700, 800, 1200

**Comment by reimersa** [comment]
I will just delete those files.

**Comment by reimersa** [comment]
done

**Pull request merged**
