### PR TITLE
Signal samples for ttbar res searches

### PR DESCRIPTION
**Pull request by kdeleo**

### CODE REVIEW

**Comment by MatthiesC** [comment]
Hi @kdeleo ! You did not include the ttbar res samples in the CrossSectionHelper database. Is this intended?

**Comment by kdeleo** [comment]
> Hi @kdeleo ! You did not include the ttbar res samples in the CrossSectionHelper database. Is this intended?

Hi, yes I left them out of the CrossSectionHelper to not increase too much the size of the file. I have a copy of the database with my signals only, but I can add them to the common database if you think that's better

**Comment by MatthiesC** [comment]
With this PR you added ca. 500 XML files, equalling ca. 125 dict entries in the database (500 divided by 4 because of the years). This would be quite a lot indeed. How large is your signal-only copy of the python file in Kilobytes? We need to remember that files above 1 MB cannot be properly displayed by GitHub. This would be the breaking point.
If you can live with your private copy I would be in favor to not include them in the Helper for now.

**Comment by MatthiesC** [comment]
BTW we could open an Issue to keep being aware of this and document that the ttbar res samples are not part of the CrossSectionHelper

**Comment by kdeleo** [comment]
Now it's about the same size as the common CrossSectionHelper, but I will add ~120 more xml files with the corresponding entries to the database

**Comment by MatthiesC** [comment]
Okay. But then we should still be way below 1 MB. Right now the CrossSectionHelper (CSH) is at ca. 240 KB and doubling it makes ca. 0.5 MB. Then it is okay to include your signals in the CSH I guess. (Unless other people raise their voice.)

I would suggest to merge this PR now. Could you take care of adding the ttbar res samples to CSH when adding the remaing ttbar res samples you just mentioned?

**Comment by kdeleo** [comment]
Sounds good!

**Pull request merged**
