### PR TITLE
Reproduce and count DoubleMuon 18 A and D

### PR DESCRIPTION
**Pull request by danielhundhausen**
This is at least the 3rd time I'm trying to produce 18 D, no jobs fail and the event count is < #Events on DAS. Thus, I propose to merge.

### CODE REVIEW

**Comment by finnlabe** [comment]
Do I see correctly that we are missing < 0.01% of events? If thats the case, I'd agree that we can merge.

**Comment by jabuschh** [comment]
@MatthiesC, you observed a similar thing for `/SingleMuon/Run2018A-UL2018_MiniAODv2_GT36-v1/MINIAOD`, right?
If one checks [here](https://pdmv-pages.web.cern.ch/rereco_ul/), there are several data samples missing very few events. Maybe we can just report it?

**Comment by danielhundhausen** [comment]
> Do I see correctly that we are missing < 0.01% of events? If thats the case, I'd agree that we can merge.

It's 0.00104 %

**Comment by MatthiesC** [comment]
For SingleMuon UL18 Run A there also is a delta of 5292 events between DAS and PNFS although all jobs finished. That number is actually reported somewhere here: https://pdmv-pages.web.cern.ch/rereco_ul/ Might be that there is something similar going on for DoubleMuon UL18 Run D, I don't know. Regardless, I think that 0.001 % is negligible unless you are explicitly searching for an individual event...

**Pull request merged**
