### PR TITLE
2018 VV diboson samples, inclusive or with hadronic decays

### PR DESCRIPTION
**Pull request by IreneZoi**
note: in /pnfs/desy.de/cms/tier2/store/group/uhh/uhh2ntuples/RunII_102X_v2/2018/ there are also other such diboson samples but I didn't find trace of them in the xmls or in the google doc so I realised it only after producing them.. some cleaning or further xml production may be needed to spare storage memory and to avoid that other people reprocess sample already processed by someone else..

### CODE REVIEW

**Comment by raggleton** [comment]
Re: the other samples: we can do some Sherlock-ing with grafana... 
e.g. let's use `/pnfs/desy.de/cms/tier2/store/group/uhh/uhh2ntuples/RunII_102X_v2/2018/WWToLNuQQ_NNPDF31_TuneCP5_13TeV-powheg-pythia8/crab_WWToLNuQQ_NNPDF31_TuneCP5_13TeV-powheg-pythia8_Autumn18_v1//200324_220127/` directory, which isn't in your XMLs.

If we go on the CMS Tasks Monitoring Global view on grafana (https://monit-grafana.cern.ch/d/cmsTMGlobal/cms-tasks-monitoring-globalview?orgId=11), then we filter by date and time using `200324_220127` from the filepath: this means the job was created on the 24th March 2020, at 22:01:27. So if we put a time & date filter around that (it's a button at the top right of the webpage), we get e.g. https://monit-grafana.cern.ch/d/cmsTMGlobal/cms-tasks-monitoring-globalview?orgId=11&from=1585087260000&to=1585087379000&var-user=All&var-site=All&var-current_url=%2Fd%2FcmsTMDetail%2Fcms_task_monitoring&var-task=All
revealing the jobs were done by @anmalara

**Comment by IreneZoi** [comment]
actually.. now that you mentioned it.. maybe he mentioned to me that he was going to produce some samples.. but I totally forgot about it..

**Comment by anmalara** [comment]
Yes I did. I need to check why those are not merged/ in the data-sheet, because I though I did.
For the 2017, I didn't push the xml files, but in principle I added the entries in the data-sheet.

**Comment by anmalara** [comment]
Apparently the xmls were never pushed. I'm sorry about this.
But I'm pretty sure I put the entries in the spreadsheet. I must become old!
Maybe we should change way of storing the info to something that keeps track of changes.
In any case, this is the list of files that I have:

RunII_102X_v2/2018/DYJetsToLL_M-50_HT-70to100_TuneCP5_PSweights_13TeV-madgraphMLM-pyt_Autumn18_v1.xml
RunII_102X_v2/2018/WWTo1L1Nu2Q_13TeV_amcatnloFXFX_madspin_pythia8_Autumn18_v1.xml
RunII_102X_v2/2018/WWTo2L2Nu_NNPDF31_TuneCP5_13TeV-powheg-pythia8_Autumn18_v1.xml
RunII_102X_v2/2018/WWTo4Q_NNPDF31_TuneCP5_13TeV-powheg-pythia8_Autumn18_v1.xml
RunII_102X_v2/2018/WWToLNuQQ_NNPDF31_TuneCP5_13TeV-powheg-pythia8_Autumn18_v1.xml
RunII_102X_v2/2018/WZTo1L1Nu2Q_13TeV_amcatnloFXFX_madspin_pythia8_Autumn18_v1.xml
RunII_102X_v2/2018/WZTo1L3Nu_13TeV_amcatnloFXFX_madspin_pythia8_Autumn18_v1.xml
RunII_102X_v2/2018/WZTo2L2Q_13TeV_amcatnloFXFX_madspin_pythia8_Autumn18_v1.xml
RunII_102X_v2/2018/WZTo3LNu_0Jets_MLL-50_CP5_Autumn18_v2.xml
RunII_102X_v2/2018/WZTo3LNu_1Jets_MLL-50_CP5_Autumn18_v2.xml
RunII_102X_v2/2018/WZTo3LNu_2Jets_MLL-50_CP5_Autumn18_v2.xml
RunII_102X_v2/2018/WZTo3LNu_3Jets_MLL-50_CP5_Autumn18_v2.xml
RunII_102X_v2/2018/WZTo3LNu_TuneCP5_13TeV-powheg-pythia8_Autumn18_ext1_v2.xml
RunII_102X_v2/2018/ZZTo2L2Nu_TuneCP5_13TeV_powheg_pythia8_Autumn18_ext1_v2.xml
RunII_102X_v2/2018/ZZTo2L2Nu_TuneCP5_13TeV_powheg_pythia8_Autumn18_ext2_v2.xml
RunII_102X_v2/2018/ZZTo2L2Q_13TeV_amcatnloFXFX_madspin_pythia8_Autumn18_v1.xml
RunII_102X_v2/2018/ZZTo2Q2Nu_TuneCP5_13TeV_amcatnloFXFX_madspin_pythia8_Autumn18_v1.xml
RunII_102X_v2/2018/ZZTo4L_TuneCP5_13TeV_powheg_pythia8_Autumn18_ext2_v2.xml

RunII_102X_v2/2017/DYJetsToLL_M-50_HT-70to100_CP5_Fall17_v1.xml
RunII_102X_v2/2017/TTToHadronic_TuneCP5_PSweights_13TeV-powheg-pythia8_Fall17_v1.xml
RunII_102X_v2/2017/WWTo4Q_NNPDF31_TuneCP5_13TeV-powheg-pythia8_Fall17_v1.xml
RunII_102X_v2/2017/WZTo1L1Nu2Q_13TeV_amcatnloFXFX_madspin_pythia8_Fall17_v2.xml
RunII_102X_v2/2017/ZZTo2Q2Nu_TuneCP5_13TeV_amcatnloFXFX_madspin_pythia8_Fall17_v1.xml


I put 2018 and 2017 in the same thread, just to have the discussion in one single place.
Those are produced from 102x_v2 with leadingjetConstits.
Sorry for the double production, but @IreneZoi we discussed that I was going to process those ;-)

**Comment by IreneZoi** [comment]
Yes we discussed, I forgot and to my excuse you didn't enter nor your name nor the events number in the google doc.. I checked the history of a few cells in the 2017 and 2018 diboson samples production and the history says that the changes made before mine (appears as anonymous user, in 20 something April 2020) are made by Robin.. 
So now let's find a solution! 
I would suggest that @anmalara adds the xmls of the samples I didn't process and then, when we have the full picture, someone to be decided removes the duplicates..
BTW I also processed them with constituents..

**Comment by raggleton** [comment]
OK merging this one, then @anmalara will sort out duplicates

**Pull request merged**
