### PR TITLE
TTBar full leptonic decay samples

### PR DESCRIPTION
**Pull request by V8-Bjoern**

### CODE REVIEW

**Comment by raggleton** [comment]
Hi, since this is a POWHEG sample, did you check the event count when using weights? I suspect it may give a different answer to using the "fast" method (which doesn't account for the event weight)

**Comment by V8-Bjoern** [comment]
Hi, yes Andrea checked it. It's the same number.

**Comment by anmalara** [comment]
So I produced the sample. I was also surprised by the numbers, but that's the way it is. For some reason, the c++ version was crashing for some unknown reason that I couldn't isolate. I used the previous python implementation and that's the outcome.

**Comment by raggleton** [comment]
Hmm yes looking at the ntuples, and also at the MINIAOD, it looks like all the weights are 1.

**Pull request merged**
