### PR TITLE
[106X] rerecount WJetsToLNu samples

### PR DESCRIPTION
**Pull request by jabuschh**
I recounted the WJetsToLNu samples after the second dCache issues.
The total loss per sample is on average ~1-3% (max. 3.6%), see our google doc.

### CODE REVIEW

**Comment by MatthiesC** [comment]
For preVFP 400to600 the number of events changed but not the sum of weights. This does not seem to be possible to me. Can you check?

**Comment by jabuschh** [comment]
Good catch, @MatthiesC!
I recounted (fast method) and now it's the same.

**Comment by jabuschh** [comment]
Please don't merge yet!
I will do a fast recounting again to see if there were some files commented out wrongly.
Fast recounting should be sufficient in this case since all event weights are 1 for these samples.

**Comment by jabuschh** [comment]
Indeed there were two wrongly commented files (one we didn't spot before).
Now everything should be fine.

**Pull request merged**
